#!/usr/bin/env bash
# loops from 1 to 10 but with a condition.
n=0
while [ $n -lt 10 ];
do
        if [ $n -eq 9 ];
        then
            echo Hi
        fi
            echo Best School
        ((n++))
done
